server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/badge_membership_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: server-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
